### ISSUE TITLE
[Bug] Installing in wrong directory

### ISSUE THREAD

**Issue by Avaray** [danielkermode/gvm#5]
For example, this is my GOROOT path: `C:\PROGRAMMING\GO`
If I will use command `gvm install 1.8` it will download and unpack Go into `C:\PROGRAMMING`
If I set GOROOT path for `C:\PROGRAMMING\GO\GO` it will download and unpack into `C:\PROGRAMMING\GO`

GVM is always installing one directory above. Im using Win 8.1. I don't know why is like that.

**Comment by danielkermode** [comment]
Sorry, I haven't maintained this project hence the very late reply. However this is the expected behaviour. `gvm install` downloads files _adjacent_ to your GOROOT as I explain in the readme. Reason for this is to keep all Go versions in the same directory, and then other `gvm` commands look in this directory. GOROOT will be set to one of these directories, and `gvm use` will switch GOROOT between folders in this directory.
